/**
 * Demo business: Tallyforge, a fictional accounts-payable automation
 * platform for mid-market finance teams. All names are invented.
 */
import type { BrandBrain } from '../types.ts'

export function seedBrand(now: string): BrandBrain {
  return {
    company: 'Tallyforge',
    oneLiner: 'Accounts-payable automation for finance teams that have outgrown spreadsheets and email approvals.',
    mission: 'Give every finance team a close they can trust — without the chasing.',
    website: 'tallyforge.example',
    positioning: {
      category: 'AP automation',
      forWho: 'Controllers and finance leads at 200–2,000 person companies',
      problem: 'Invoices live in inboxes, approvals stall, and month-end turns into a chase',
      alternative: 'Spreadsheets plus email approvals, or the AP module bolted onto the ERP',
      differentiator: 'Live in 14 days with no ERP changes, and every invoice has an owner and a deadline',
      statement:
        'For controllers who are tired of chasing approvals, Tallyforge is the AP automation platform that goes live in 14 days without touching your ERP — so month-end closes on time and every invoice has an owner.',
    },
    offers: [
      {
        id: 'off_platform',
        name: 'Tallyforge Platform',
        kind: 'product',
        description: 'Invoice capture, approval routing, vendor payments and audit trail, synced to your ERP.',
        price: { amount: 24000, currency: 'USD', period: 'year' },
        priceTier: 'enterprise',
        purchaseComplexity: 'complex',
        guarantee: 'Live in 14 days or your first quarter is free',
        cta: 'Book a strategy call',
        outcomes: ['Close the books in days, not weeks', 'Stop paying vendors late', 'Know exactly where every invoice stands'],
        features: [
          { name: 'Approval routing', benefit: 'Every invoice has an owner and a deadline, so nothing sits in an inbox' },
          { name: 'ERP sync (NetSuite, QuickBooks, Xero)', benefit: 'No re-keying and no ERP changes' },
          { name: 'Duplicate detection', benefit: 'Catch double payments before they leave the bank' },
          { name: 'Audit trail', benefit: 'Hand auditors a complete paper trail in minutes' },
          { name: 'Vendor portal', benefit: 'Vendors check payment status themselves instead of emailing you' },
        ],
      },
      {
        id: 'off_calculator',
        name: 'AP Cost Calculator',
        kind: 'lead_magnet',
        description: 'A 3-minute calculator that estimates what manual AP costs your team per year.',
        priceTier: 'low',
        purchaseComplexity: 'simple',
        cta: 'Calculate your AP cost',
        outcomes: ['See the real cost of manual AP', 'Get a number to take to your CFO'],
        features: [],
      },
      {
        id: 'off_demo',
        name: 'Guided demo',
        kind: 'demo',
        description: 'A 30-minute walkthrough using your own invoice volumes and approval chain.',
        priceTier: 'low',
        purchaseComplexity: 'simple',
        cta: 'See it with your invoices',
        outcomes: ['See your approval chain running in Tallyforge'],
        features: [],
      },
    ],
    segments: [
      {
        id: 'seg_midmarket',
        name: 'Mid-market controllers',
        description: 'Controllers and AP leads at 200–1,000 person companies running NetSuite or QuickBooks, 800–5,000 invoices a month.',
        awareness: 'solution_aware',
        sophistication: 4,
        industries: ['logistics', 'manufacturing', 'healthcare', 'professional services'],
        jobTitles: ['Controller', 'AP Manager', 'Finance Manager'],
        priority: 'primary',
        keywords: ['controller', 'ap manager', 'mid-market', 'netsuite', 'quickbooks'],
      },
      {
        id: 'seg_enterprise',
        name: 'Enterprise finance ops',
        description: 'VP Finance and CFO offices at 1,000–5,000 person, multi-entity companies with an existing ERP and an IT review process.',
        awareness: 'product_aware',
        sophistication: 5,
        industries: ['manufacturing', 'retail', 'logistics'],
        jobTitles: ['VP Finance', 'CFO', 'Director of Finance Operations'],
        priority: 'secondary',
        keywords: ['enterprise', 'multi-entity', 'cfo', 'vp finance', 'global'],
      },
    ],
    personas: [
      {
        id: 'per_controller',
        segmentId: 'seg_midmarket',
        name: 'Dana, the stretched controller',
        role: 'Controller',
        goals: ['Close in under 5 days', 'Stop being the approval bottleneck', 'Walk into the audit calm'],
        fears: ['A missed payment damaging a key vendor relationship', 'Another tool the team won’t adopt'],
        quote: 'I spend the last week of every month chasing people for approvals.',
      },
      {
        id: 'per_vp',
        segmentId: 'seg_enterprise',
        name: 'Marcus, the VP who owns the numbers',
        role: 'VP Finance',
        goals: ['Consistent controls across entities', 'Real-time liability visibility', 'A defensible business case'],
        fears: ['A six-month implementation that stalls', 'IT blocking the project'],
        quote: 'I can’t take anything to the CFO without a payback number.',
      },
    ],
    voice: {
      traits: ['Plain-spoken', 'Specific', 'Calm under pressure', 'Finance-literate'],
      tone: 'Direct and reassuring — a senior controller talking to a peer, never a hype-driven vendor.',
      wordsToUse: ['close', 'owner', 'deadline', 'on time', 'paper trail', 'chase', 'approval'],
      wordsToAvoid: ['revolutionize', 'game-changer', 'seamless', 'synergy', 'cutting-edge', 'best-in-class', 'leverage', 'unlock', 'empower', 'AI-powered magic'],
      substitutions: { leverage: 'use', seamless: 'smooth', seamlessly: 'smoothly', utilize: 'use', empower: 'help', unlock: 'get', revolutionize: 'change', 'best-in-class': 'proven' },
      targetReadingGrade: 8,
      formality: 3,
      rules: [
        'Lead with the reader’s problem or outcome, never with Tallyforge.',
        'Every number must come from approved proof.',
        'No exclamation marks in headlines.',
        'Say “invoices”, not “documents”; say “approval”, not “workflow event”.',
        'Name the alternative (spreadsheets, email approvals) rather than attacking competitors by name.',
      ],
      exemplars: [
        { text: 'Every invoice gets an owner and a deadline. Month-end stops being a chase.', note: 'Short, concrete, names the outcome.' },
        { text: 'Live in 14 days. No ERP changes. Your team keeps working the whole time.', note: 'Answers implementation anxiety with specifics.' },
      ],
    },
    claims: [
      { id: 'clm_14days', text: 'Live in 14 days', status: 'approved', proofIds: ['prf_impl'] },
      { id: 'clm_close', text: 'Close the books in 4 days instead of 9', status: 'approved', proofIds: ['prf_harbor'] },
      { id: 'clm_late', text: '78% fewer late payments', status: 'approved', proofIds: ['prf_late'] },
      { id: 'clm_payback', text: 'Pays for itself in under 5 months', status: 'approved', proofIds: ['prf_payback'] },
      { id: 'clm_ai', text: 'Fully autonomous AI accounts payable', status: 'prohibited', proofIds: [] },
      { id: 'clm_fraud', text: 'Eliminates all payment fraud', status: 'prohibited', proofIds: [] },
      { id: 'clm_cheapest', text: 'Cheapest AP tool on the market', status: 'needs_proof', proofIds: [] },
    ],
    proof: [
      {
        id: 'prf_harbor',
        kind: 'case_study',
        title: 'Harbor Freightways closes in 4 days instead of 9',
        detail:
          'A 600-person logistics company processing 4,200 invoices a month moved approvals out of email. Month-end close went from 9 days to 4, and the AP team stopped working the last weekend of every month.',
        customer: 'Harbor Freightways',
        metric: { label: 'Month-end close', value: '9 days → 4 days' },
        segmentIds: ['seg_midmarket'],
      },
      {
        id: 'prf_late',
        kind: 'metric',
        title: '78% fewer late payments',
        detail: 'Across customers live for 6+ months, late vendor payments fell 78% compared with their first month.',
        metric: { label: 'Late payments', value: '−78%' },
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
      {
        id: 'prf_impl',
        kind: 'metric',
        title: 'Live in 14 days on average',
        detail: 'Median time from kickoff to first invoice approved in production is 14 days, with no changes to the customer’s ERP.',
        metric: { label: 'Time to live', value: '14 days' },
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
      {
        id: 'prf_payback',
        kind: 'metric',
        title: 'Payback in under 5 months',
        detail: 'Median payback period across 40 mid-market customers, counting AP hours saved, late fees avoided and early-payment discounts captured.',
        metric: { label: 'Median payback', value: '4.6 months' },
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
      {
        id: 'prf_northwind',
        kind: 'testimonial',
        title: 'Priya Raman, VP Finance, Northwind Components',
        detail: '“We were live across three entities in under three weeks. IT signed off in one meeting because nothing touched the ERP.”',
        customer: 'Northwind Components',
        segmentIds: ['seg_enterprise'],
      },
      {
        id: 'prf_brightsmile',
        kind: 'case_study',
        title: 'BrightSmile Dental Group: invoice approvals in 2 days, not 9',
        detail:
          'An 11-location dental group was approving supply and lab invoices by email between practice managers and the central office. Approvals now take 2 days instead of 9, and the office manager no longer chases each practice.',
        customer: 'BrightSmile Dental Group',
        metric: { label: 'Approval time', value: '9 days → 2 days' },
        segmentIds: ['seg_midmarket'],
      },
      {
        id: 'prf_g2',
        kind: 'review_rating',
        title: '4.8 / 5 from 212 reviews',
        detail: 'Average rating across 212 verified reviews on independent software review sites.',
        metric: { label: 'Rating', value: '4.8 / 5' },
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
      {
        id: 'prf_guarantee',
        kind: 'guarantee',
        title: 'Live in 14 days or your first quarter is free',
        detail: 'If you are not approving invoices in production 14 days after kickoff, the first quarter of your subscription is free.',
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
    ],
    competitors: [
      {
        id: 'cmp_status_quo',
        name: 'Spreadsheets and email',
        kind: 'status_quo',
        aliases: ['spreadsheet', 'excel', 'by email', 'email threads', 'email approvals'],
        positioning: 'Free, familiar, already in place.',
        strengths: ['No cost', 'No change management'],
        weaknesses: ['No owner or deadline per invoice', 'No audit trail', 'Approvals stall in inboxes'],
      },
      {
        id: 'cmp_erp',
        name: 'ERP AP module',
        kind: 'indirect',
        aliases: ['ERP module', 'AP module'],
        positioning: 'Already bundled with the ERP.',
        strengths: ['Single vendor', 'Native data model'],
        weaknesses: ['Months of configuration', 'Clunky approval UX that approvers avoid'],
      },
      {
        id: 'cmp_billnest',
        name: 'Billnest',
        kind: 'direct',
        positioning: 'Low-cost AP automation for small businesses.',
        strengths: ['Cheap entry price', 'Fast self-serve setup'],
        weaknesses: ['Breaks down past a few hundred invoices a month', 'No multi-entity support'],
      },
      {
        id: 'cmp_ledgerlane',
        name: 'Ledgerlane',
        kind: 'direct',
        positioning: 'Enterprise spend-management suite.',
        strengths: ['Broad suite', 'Big-brand logos'],
        weaknesses: ['Six-month implementations', 'Priced for the Fortune 500'],
      },
    ],
    pillars: [
      {
        id: 'pil_owner',
        name: 'Every invoice has an owner',
        statement: 'Approvals route to a named person with a deadline, so nothing stalls in an inbox.',
        proofIds: ['prf_harbor', 'prf_brightsmile'],
        segmentIds: ['seg_midmarket'],
      },
      {
        id: 'pil_fast',
        name: 'Live in 14 days',
        statement: 'No ERP changes, no six-month project — your team is approving invoices in two weeks.',
        proofIds: ['prf_impl', 'prf_northwind', 'prf_guarantee'],
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
      {
        id: 'pil_payback',
        name: 'Pays for itself',
        statement: 'Hours saved, late fees avoided and discounts captured pay back the platform in under five months.',
        proofIds: ['prf_payback', 'prf_late'],
        segmentIds: ['seg_midmarket', 'seg_enterprise'],
      },
    ],
    updatedAt: now,
  }
}
